services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: digitizer-api
    ports:
      - "${PORT:-3000}:3000"
    # This command reads your local .env file and passes the variables to the container
    env_file:
      - .env
    volumes:
      # Mount source code for hot-reloading
      - ./src:/app/src
      # Mount Google Cloud credentials securely
      - ./handwriting-digitizer-v2-98c01506bdae.json:/app/handwriting-digitizer-v2-98c01506bdae.json:ro
    command: npm run dev
